--Vendas - tudo (limite período)
SELECT 
C.PROTOCOLO,
COUNT(CI.*),
C.FRETE,
C.VL_TOTAL,
C.DT_TRANSACAO
FROM CARRINHO AS C
INNER JOIN CARRINHOITEM AS CI
ON CI.CARIINHO_ID = C.ID
WHERE DT_TRANSACAO BETWEEN x AND y

--Vendas - tudo feminino (limite período)
SELECT 
C.PROTOCOLO,
COUNT(CI.*),
C.FRETE,
C.VL_TOTAL,
C.DT_TRANSACAO
FROM CARRINHO AS C
INNER JOIN CARRINHOITEM AS CI
ON CI.CARIINHO_ID = C.ID
INNER JOIN PRODUTO AS P
ON P.ID = CI.PRODUTO_ID
INNER JOIN CATEGORIA AS CT
ON CT.ID = P.CATEGORIA_ID AND CT.GENERO = 'F'
WHERE DT_TRANSACAO BETWEEN x AND y

--Vendas - tudo masculino (limite período)
SELECT 
C.PROTOCOLO,
COUNT(CI.*),
C.FRETE,
C.VL_TOTAL,
C.DT_TRANSACAO
FROM CARRINHO AS C
INNER JOIN CARRINHOITEM AS CI
ON CI.CARIINHO_ID = C.ID
INNER JOIN PRODUTO AS P
ON P.ID = CI.PRODUTO_ID
INNER JOIN CATEGORIA AS CT
ON CT.ID = P.CATEGORIA_ID AND CT.GENERO = 'M'
WHERE DT_TRANSACAO BETWEEN x AND y


--Vendas - por categoria (limite período)
SELECT 
C.PROTOCOLO,
COUNT(CI.*),
C.FRETE,
C.VL_TOTAL,
C.DT_TRANSACAO
FROM CARRINHO AS C
INNER JOIN CARRINHOITEM AS CI
ON CI.CARIINHO_ID = C.ID
INNER JOIN PRODUTO AS P
ON P.ID = CI.PRODUTO_ID
INNER JOIN CATEGORIA AS CT
ON CT.ID = P.CATEGORIA_ID
WHERE DT_TRANSACAO BETWEEN x AND y
