CREATE VIEW SELECT_DETALHE_PEDIDO
(
    ID_COMPRA
    ,PROTOCOLO
    ,QUANTIDADE
    ,PRODUTO_ID
    ,NOME_PRODUTO
    ,VALOR
    ,NOME AS NOME_CLIENTE
)
AS 
SELECT
    c.ID AS ID_COMPRA,
    c.PROTOCOLO,
    ci.QUANTIDADE,
    p.ID AS PRODUTO_ID,
    p.NOME AS NOME_PRODUTO,
    p.VALOR,
    ct.NOME AS NOME_CLIENTE
FROM carrinho c
INNER JOIN carrinhoitem ci ON ci.CARRINHO_ID = c.ID
INNER JOIN cliente ct ON ct.ID = c.CLIENTE_ID
INNER JOIN produto p on p.ID = ci.PRODUTO_ID