-- CREATE TABLE
CREATE TABLE CATEGORIA (

ID INT NOT NULL AUTO_INCREMENT,
GENERO CHAR NOT NULL,
NOME VARCHAR(50) NOT NULL,
PRIMARY KEY (ID)

) DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
CREATE TABLE Colecao
(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,    
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
CREATE TABLE Marca
(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
CREATE TABLE Produto
(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(100),
    ID_CATEGORIA INT NOT NULL,
    ID_MARCA INT NOT NULL,
    ID_COLECAO INT NOT NULL,
    VALOR DOUBLE NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE,
    DT_CADASTRO DATETIME DEFAULT NOW(),
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES Categoria(ID),
    FOREIGN KEY (ID_COLECAO) REFERENCES Colecao(ID),
    FOREIGN KEY (ID_MARCA) REFERENCES Marca(ID)
) DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
CREATE TABLE Estoque
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    TAMANHO VARCHAR(5) NOT NULL,
    PRIMARY KEY (ID, ID_PRODUTO, TAMANHO),
    FOREIGN KEY (ID_PRODUTO)  REFERENCES PRODUTO(ID)
) DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
CREATE TABLE ProdutoImagem
(
    ID INT NOT NULL AUTO_INCREMENT,
    ID_PRODUTO INT NOT NULL,
    Nome VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID, ID_PRODUTO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES Produto(ID)
) DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE TABLE Cliente (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    EMAIL VARCHAR(50) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    SEXO CHAR,
    TELEFONE VARCHAR(12),
    CELULAR VARCHAR(13) NOT NULL,
    SENHA VARCHAR(200) NULL,
    ATIVO BOOLEAN DEFAULT TRUE,
    DT_CADASTRO DATETIME DEFAULT NOW(),    
    PRIMARY KEY (ID, CPF)
) DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
CREATE TABLE ENDERECO(

    ID INT NOT NULL AUTO_INCREMENT,
    CLIENTE_ID INT NOT NULL,
    LOGRADOURO VARCHAR (100) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR (50),
    CIDADE VARCHAR(50) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    CEP VARCHAR (9) NOT NULL,
    PRINCIPAL BOOLEAN DEFAULT FALSE,
    ATIVO BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (ID, CLIENTE_ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)

) DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
CREATE TABLE Perfil
(
    ID INT NOT NULL UNIQUE,
    Nome VARCHAR(50) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
CREATE TABLE Usuario
(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100),
    LOGIN VARCHAR(30) NOT NULL UNIQUE,
    SENHA VARCHAR(10000) NOT NULL,
    ID_PERFIL INT NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    DT_CADASTRO DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_PERFIL) REFERENCES Perfil(ID)
) DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
CREATE TABLE CARRINHO
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    DT_TRANSACAO DATETIME NOT NULL DEFAULT NOW(),
    USUARIO_ID INT,
    CLIENTE_ID INT NOT NULL,
    VL_TOTAL DECIMAL(9, 2) NOT NULL,
    PROTOCOLO BIGINT,
    PRIMARY KEY(ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
) DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE TABLE CARRINHOITEM
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CARRINHO_ID BIGINT NOT NULL,
    PRODUTO_ID INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    TAMANHO VARCHAR(5) NOT NULL,
    VL_ITEM DECIMAL(9, 2) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CARRINHO_ID) REFERENCES CARRINHO(ID)
) DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE TABLE TICKETSAC
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    DT_TRANSACAO DATETIME NOT NULL DEFAULT NOW(),
    CLIENTE_ID INT NOT NULL,
    PROTOCOLO BIGINT,
	DESCRICAO VARCHAR(60) NOT NULL,
	TIPO_ERRO VARCHAR(30) NOT NULL,
	STATUS VARCHAR(10) NOT NULL DEFAULT 'PENDENTE',
    PRIMARY KEY(ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
) DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE TABLE promocao
(
    ID INT NOT NULL AUTO_INCREMENT,
    PRODUTO_ID INT NOT NULL,
    DT_INICIO DATETIME NOT NULL DEFAULT NOW(),
    DT_FIM DATETIME,
    PERC_DESCONTO DOUBLE NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES produto(ID)
) DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
-- FIM CREATE TABLE

-- INSERT 
INSERT INTO CATEGORIA (GENERO, NOME) VALUES 
    ('F', 'Blusa'), ('F', 'Camisa'), ('F', 'Camiseta'), ('F', 'Moletom'),
    ('F', 'Casaco'), ('F', 'Jaqueta'), ('F', 'Tricô´'), ('F', 'Calça'), ('F', 'Bermuda'),
    ('F', 'Saia'), ('F', 'Legging'), ('F', 'Vestido'), ('F', 'Macacão'), ('F', 'Jardineira'),
    ('M', 'Blusa'), ('M', 'Camisa'), ('M', 'Camiseta'),   ('M', 'Moletom'),  ('M', 'Casaco'),  
    ('M', 'Jaqueta'), ('M', 'Tricô'),  ('M', 'Calça'),   ('M', 'Bermuda'),  ('M', 'Legging'), 
    ('M', 'Macacão'),    ('M', 'Jardineira');

INSERT INTO COLECAO (NOME) 
    VALUES 
    ('Casual 2k17'), ('Prima Vera'), ('Verão Verão');

INSERT INTO MARCA (NOME) 
    VALUES 
    ('Calvin Klein'), ('Aramis'), ('Lacoste'), ('Joss'), ('Reserva'), 
    ('Tommy Hilfiger'), ('Colcci'), ('Billabong');

INSERT INTO PRODUTO (NOME, DESCRICAO, ID_CATEGORIA, ID_MARCA, ID_COLECAO, VALOR) 
    VALUES
    ('produto teste 1', 'descricao do produto teste 1', 1, 1, 1, 87.79),
    ('produto teste 2', 'descricao do produto teste 2', 12, 5, 3, 57.30),
    ('produto teste 3', 'descricao do produto teste 3', 20, 7, 3, 99.90),
    ('produto teste 4', 'descricao do produto teste 3', 9, 7, 3, 99.90),
    ('produto teste 5', 'descricao do produto teste 3', 17, 7, 3, 99.90);

INSERT INTO Perfil (ID, NOME)
    VALUES 
    (100, 'Administrador'),
    (200, 'Gestor Backoffice'),
    (210, 'Operador Backoffice'),
    (300, 'Operacao');

INSERT INTO cliente (NOME, CPF, EMAIL, DT_NASCIMENTO, SEXO, TELEFONE, CELULAR, SENHA)
    VALUES ('Cliente 001', '21233366898', 'cliente001@email.com','1994-01-01' ,'F', '123456', '654321', '123');

INSERT INTO promocao (PRODUTO_ID, DT_INICIO, DT_FIM, PERC_DESCONTO)
    VALUES
    (1, NOW(), NULL, 10.0)
    , (2, NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY), 50.0)
    , (3, NOW(), NULL, 15.0)
    , (4, DATE_ADD(NOW(), INTERVAL -60 DAY), DATE_ADD(NOW(), INTERVAL -55 DAY), 80.0)
    , (4, DATE_ADD(NOW(), INTERVAL -54 DAY), DATE_ADD(NOW(), INTERVAL 5 DAY), 80.0);
-- FIM INSERT