CREATE TABLE Produto
(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(100),
    ID_MARCA INT NOT NULL,
    ID_COLECAO INT NOT NULL,
    VALOR DOUBLE NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE,
    DT_CADASTRO DATETIME DEFAULT NOW(),

    PRIMARY KEY (ID),
    FOREIGN KEY (ID_COLECAO) REFERENCES Colecao(ID),
    FOREIGN KEY (ID_MARCA) REFERENCES Marca(ID)
);