CREATE TABLE Estoque
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    TAMANHO VARCHAR(5) NOT NULL,

    PRIMARY KEY (ID, ID_PRODUTO, TAMANHO),
    FOREIGN KEY (ID_PRODUTO)  REFERENCES PRODUTO(ID)
)