CREATE TABLE Estoque
(
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    TAMANHO VARCHAR(5) NOT NULL,

    PRIMARY KEY (ID, ID_PRODUTO, TAMANHO),
    FOREIGN KEY (ID_PRODUTO)  REFERENCES PRODUTO(ID)
)