CREATE TABLE ProdutoImagem
(
    ID INT NOT NULL AUTO_INCREMENT,
    ID_PRODUTO INT NOT NULL,
    Nome VARCHAR(50) NOT NULL,

    PRIMARY KEY (ID, ID_PRODUTO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES Produto(ID)
);