CREATE TABLE Cliente (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    EMAIL VARCHAR(50) NOT NULL,
    DT_NASCIMENTO DATE,
    SEXO CHAR,
    TELEFONE VARCHAR(12),
    CELULAR VARCHAR(13) NOT NULL,
    SENHA VARCHAR(20) NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE,
    DT_CADASTRO DATETIME DEFAULT NOW(),
    
    PRIMARY KEY (ID, CPF)
);