CREATE TABLE Usuario
(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100),
    LOGIN VARCHAR(30) NOT NULL UNIQUE,
    SENHA VARCHAR(10000) NOT NULL,
    ID_PERFIL INT NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    DT_CADASTRO DATETIME NOT NULL DEFAULT NOW(),

    PRIMARY KEY (ID),
    FOREIGN KEY (ID_PERFIL) REFERENCES Perfil(ID)
);