CREATE TABLE CARRINHO
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    DT_TRANSACAO DATETIME NOT NULL DEFAULT NOW(),
    USUARIO_ID INT NULL,
    CLIENTE_ID INT NOT NULL,
    VL_TOTAL DECIMAL(9, 2) NOT NULL,

    PRIMARY KEY(ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

CREATE TABLE CARRINHOITEM
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CARRINHO_ID BIGINT NOT NULL,
    PRODUTO_ID INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    TAMANHO VARCHAR(5) NOT NULL,
    VL_ITEM DECIMAL(9, 2) NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (CARRINHO_ID) REFERENCES CARRINHO(ID),    
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);