CREATE TABLE TICKETSAC
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    DT_TRANSACAO DATETIME NOT NULL DEFAULT NOW(),
    USUARIO_ID INT,
    CLIENTE_ID INT NOT NULL,
    VL_TOTAL DECIMAL(9, 2) NOT NULL,
    PROTOCOLO BIGINT,
	DESCRICAO VARCHAR(60) NOT NULL,
	TIPO_ERRO VARCHAR(30) NOT NULL,
	STATUS VARCHAR(10) NOT NULL DEFAULT 'PENDENTE',
    PRIMARY KEY(ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);