CREATE TABLE StatusCarrinhoDetalhe
(
    ID INT NOT NULL AUTO_INCREMENT,
    STATUS_ID INT NOT NULL,
    CARRINHO_ID INT NOT NULL,
    DT_CADASTRO DATETIME NOT NULL DEFAULT NOW(), 
    PRIMARY KEY (ID)
)