CREATE TABLE StatusFormularioDetalhe
(
    ID INT NOT NULL AUTO_INCREMENT,
    STATUS_ID INT NOT NULL,
    FORMULARIO_ID INT NOT NULL,
    DT_CADASTRO DATETIME NOT NULL DEFAULT NOW(), 
    PRIMARY KEY (ID)
)
