CREATE TABLE Formulario
(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(20) NULL,
    MENSAGEM VARCHAR(8000),
    DT_CADASTRO DATETIME NOT NULL DEFAULT NOW(), 
    PRIMARY KEY (ID)
)